DELETE http://localhost:3001/api/blogs/6446471e4426a67ba35cb655
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtheXR0YWphIiwiaWQiOiI2NDQ2M2IzNzNhYzFmNGMzNjk3YjY2YjUiLCJpYXQiOjE2ODIzMjc5ODF9.pYZwam5sxj6WpqHfNVXBNvI8OxNTN9kVyLTpenuHtLU